BEGIN;

CREATE TABLE IF NOT EXISTS organization
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;